import { packThumbnail } from "../assets";

 const packSamples = [
    {
      id:1,
      thumnailSrc: packThumbnail,
      sampleCaption: "This is the product one",
      price: 14.22,
      downloads: 500,
      sales: "3.5k",
      status: "active",
    },
    {
      id:2,
      thumnailSrc: packThumbnail,
      sampleCaption: "This is the product one",
      price: 14.22,
      downloads: 500,
      sales: "3.5k",
      status: "active",
    },
    {
      id:3,
      thumnailSrc: packThumbnail,
      sampleCaption: "This is the product one",
      price: 14.22,
      downloads: 500,
      sales: "3.5k",
      status: "active",
    },
    {
      id:4,
      thumnailSrc: packThumbnail,
      sampleCaption: "This is the product one",
      price: 14.22,
      downloads: 500,
      sales: "3.5k",
      status: "active",
    },
    {
      id:5,
      thumnailSrc: packThumbnail,
      sampleCaption: "This is the product one",
      price: 14.22,
      downloads: 500,
      sales: "3.5k",
      status: "active",
    },
  ];

  export const packSamplesHomePage = [
    {
      id:1,
      thumnailSrc: packThumbnail,
      sampleCaption: "This is the product one",
      price: 14.22,
      downloads: 500,
      sales: "3.5k",
      status: "active",
    },
    {
      id:2,
      thumnailSrc: packThumbnail,
      sampleCaption: "This is the product one",
      price: 14.22,
      downloads: 500,
      sales: "3.5k",
      status: "active",
    },
    {
      id:3,
      thumnailSrc: packThumbnail,
      sampleCaption: "This is the product one",
      price: 14.22,
      downloads: 500,
      sales: "3.5k",
      status: "active",
    },
    {
      id:4,
      thumnailSrc: packThumbnail,
      sampleCaption: "This is the product one",
      price: 14.22,
      downloads: 500,
      sales: "3.5k",
      status: "active",
    },
    {
      id:5,
      thumnailSrc: packThumbnail,
      sampleCaption: "This is the product one",
      price: 14.22,
      downloads: 500,
      sales: "3.5k",
      status: "active",
    },
    {
      id:6,
      thumnailSrc: packThumbnail,
      sampleCaption: "This is the product one",
      price: 14.22,
      downloads: 500,
      sales: "3.5k",
      status: "active",
    },
    {
      id:7,
      thumnailSrc: packThumbnail,
      sampleCaption: "This is the product one",
      price: 14.22,
      downloads: 500,
      sales: "3.5k",
      status: "active",
    },
    {
      id:8,
      thumnailSrc: packThumbnail,
      sampleCaption: "This is the product one",
      price: 14.22,
      downloads: 500,
      sales: "3.5k",
      status: "active",
    },
    {
      id:9,
      thumnailSrc: packThumbnail,
      sampleCaption: "This is the product one",
      price: 14.22,
      downloads: 500,
      sales: "3.5k",
      status: "active",
    },
    {
      id:10,
      thumnailSrc: packThumbnail,
      sampleCaption: "This is the product one",
      price: 14.22,
      downloads: 500,
      sales: "3.5k",
      status: "active",
    },
  ];


  
export default packSamples;
